---
- name: Lighthouse | Install git
  become: true
  ansible.builtin.yum:
    name: git
    state: present
- name: Lighthouse | Git
  become: true
  ansible.builtin.git:
    repo: https://github.com/VKCOM/lighthouse.git
    dest: /etc/lighthouse
    version: master
- name: Lighthouse | Create config
  become: true
  ansible.builtin.template:
    src: ./templates/lighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: "0644"
  notify: Restart Nginx
